name: Rspec

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          POSTGRES_DB: levitas_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: levitas  # Use the correct password from your database.yml

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby 3.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install --pure-lockfile

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Setup DB
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:levitas@localhost:5432/levitas_test  # Update the database URL
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        run: |
          bin/rails db:prepare

      - name: Run tests
        env:
          REDIS_URL: redis://127.0.0.1:6379
        run: |
          bundle exec rspec
